### ISSUE TITLE
Cursor shape change in insert mode doesn't work on default terminal and iterm2 tmux 

### ISSUE THREAD

**Issue by jojoyuji** [wincent/terminus#1]
It only worked on iterm2 without tmux. 

I dont really use iterm2 instead I prefer the default OSX terminal. It doesn't work either in default terminal and in tmux.

tmux version: 2.0
vim version: 7.4

**Comment by wincent** [comment]
Yeah, I don't think it will work in Terminal, unless Apple changes something in the future (I should probably make the docs clearer about what is/isn't supported in the different terminals).

But it should work in recent versions of iTerm, even inside tmux. I'm still on tmux 1.9a though; I haven't checked out 2.0 yet. Let me go ahead and try that.

**Comment by alexlafroscia** [comment]
I've noticed that it doesn't work with neovim (iTerm + tmux) but it seems to be working with iTerm+tmux+vim 7.4 on the same machine with the same plugins installed.

**Comment by wincent** [comment]
Yeah, I haven't tested on Neovim (have never even installed it, to be honest), but if somebody figures out how to make things work on Neovim I'd be happy to apply a patch for it.

**Comment by wincent** [comment]
Now that I've added the `TROUBLESHOOTING` section to the docs, I'm going to close this one. I've created a separate issue for Neovim support (https://github.com/wincent/terminus/issues/4). Won't create one for Terminal.app support, as that one is in Apple's hands.
