### ISSUE TITLE
E355: Unknown option: t_SR

### ISSUE THREAD

**Issue by lencioni** [wincent/terminus#10]
After updating from 928b3bfb to 10564cb4 I now get the following error when starting Vim:

```
Error detected while processing /path/to/.vim/bundle/terminus/plugin/terminus.vim:
line   58:
E355: Unknown option: t_SR
```

It turned out that I was running an old version of Vim for some reason (7.4.488) and upgrading (to 7.4.873) made this message disappear. It looks like [`t_SR` was added in 687](https://github.com/vim/vim/releases/tag/v7.4.687). I'll submit a PR shortly that guards against this.

**Comment by wincent** [comment]
Thanks for the catch and the fix.
