### ISSUE TITLE
Setting wrong variable?

### ISSUE THREAD

**Issue by vheon** [wincent/terminus#12]
I believe you've got a typo at https://github.com/wincent/terminus/blob/master/plugin/terminus.vim#L9, shouldn't it be `let g:TerminusLoaded = 1`?

**Comment by wincent** [comment]
Yes! How embarrassing. You caught me in the act of copy-pasta!

This could have been a nasty bug for users of both Terminus and Loupe, but I think alphabetical load ordering means that it all works out ok.

Will fix anyway. Thanks for the report!
