### ISSUE TITLE
bracketed paste no longer working

### ISSUE THREAD

**Issue by tnguyen14** [wincent/terminus#15]
Bracketed paste used to work for me, but have stopped working as of late. I am not sure why.

Here's my `vim --version` info:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb  8 2016 12:26:50)
MacOS X (unix) version
Included patches: 1-1265
Compiled by Homebrew
```

and

```
pastetoggle=<Esc>[201~
```

Any help/ advice would be greatly appreciated!

**Comment by wincent** [comment]
Not sure. I think I am going to need more info on how to reproduce this as it still works fine for me. Have you made any changes to your configuration or set up? (Installed other plug-ins etc)?

**Comment by tnguyen14** [comment]
Hi @wincent, sorry I never got back to you on this.

I am still seeing the problem, and here's my vimrc. I wonder if that would be helpful for you? https://github.com/tnguyen14/dotfiles/blob/master/home/.vimrc

I could also help provide any other info as needed to fix this.

**Comment by wincent** [comment]
I see you have a lot of plug-ins, some of them which look like they could potentially clash with Terminus ('tmux-plugins/vim-tmux-focus-events' and 'tmux-plugins/vim-tmux', for instance; I don't know what they do, but I am suspicious).

I'd suggest trying to bisect things down by disabling some or all of those plug-ins and then see if you can reproduce your issue. (I don't use Vundle myself, so I don't have a way of conveniently copying your set-up.) Let me know whatever you figure out. If there's something I can do to make Terminus robust against the influence of whatever it is in your set-up that is causing bracketed paste mode not to work, I'd be glad to do it.

**Comment by tnguyen14** [comment]
So I removed those 2 plugins, and paste seemed to work again for me. But then when i tried to reinstalled them one by one, neither of them seems to cause the problem again.

So now I'm back to all the plugins I have before, and unable to reproduce this problem. I'll update if I run into it again.

**Comment by tnguyen14** [comment]
Hi, the issue came back again, and I was able to confirm that removing the `vim-tmux-focus-events` fixed it.

**Comment by wincent** [comment]
Makes sense. Looks like what it does is largely duplicative of what Terminus does.

**Comment by tnguyen14** [comment]
@wincent so what would the ideal solution be? Update terminus to make it more compatible? Just not use `vim-tmux-focus-events`?

**Comment by wincent** [comment]
As far as I can tell, there is no reason to use `vim-tmux-focus-events` as Terminus already covers that functionality. Is there something I am missing?

In terms of more compatibility, about the only thing I can think of is printing a warning if `vim-tmux-focus-events` is found to be installed, but having them both installed also sounds pretty rare, so I am not sure if it is worth it.

**Comment by tnguyen14** [comment]
Ok. That seems fair. Hopefully if that's ever an issue to someone, they'll be able to google this issue. Thank you @wincent for your help and patience.

**Comment by lencioni** [comment]
It might be a good idea to add a note to the readme and documentation.

**Comment by wincent** [comment]
I'll follow the "two or more, use a for" rule on this one, as I consider this an incredibly unlikely mistake. If I see one other person report it I'll consider that a signal that I'm wrong. In the meantime I prefer to keep the clutter out of the readme.
