### ISSUE TITLE
Handle bracketed past in normal and visual mode

### ISSUE THREAD

**Issue by thalesmello** [wincent/terminus#16]
I was wondering if it would be possible to handle bracketed paste on normal mode.

Imagine the (assuming + register is linked to system clipboard):
- In normal mode, `Command + v` would `"+P`
- In visual mode, `Command + v` would `"+p`

That would make the Vim terminal behave exactly like other GUI editors.

Is something like this even possible?

**Comment by wincent** [comment]
This already works; see [here](https://github.com/wincent/terminus/blob/2c0f002391e7111d0ef07ea4f3def98820e605a5/plugin/terminus.vim#L130-L149).

For example, in normal mode, on `Command-V`, it does `:set paste`, enters insert mode, and allows the pasted text straight through (no `"+P` needed).

**Comment by thalesmello** [comment]
Strange. That does't happen on my computer.

Vim interprets the characters literally. Would you have any idea what
configuration could be missing?

Notice terminus pastes correctly (escaping the pasted text) when I'm in
insert mode.

Atenciosamente,
Thales Mello.

**Comment by thalesmello** [comment]
Nevermind. I just found the reason it does not seem to be working: I'm using Neovim.

I noticed there is an issue open. I'll take a look into it.
