### ISSUE TITLE
Weird artifacts in Terminator?

### ISSUE THREAD

**Issue by frioux** [wincent/terminus#20]
I have a pretty complex setup, feel free to peak [at my dotfiles](https://github.com/frioux/dotfiles), but basically [this commit](640509f8689a59d4620ec7d95bd0ff1cbc40d81b) causes problems in terminator.  I can reproduce the issue both in and out of tmux.  My modeline (and sometimes autocomplete menus) end up with characters like `[2 q` or `[6 q` inserted all over the place.  Let me know if there's anything I can do to help.

**Comment by wincent** [comment]
That commit link isn't working for me. Got another?

**Comment by frioux** [comment]
Weird! This is it:
https://github.com/wincent/terminus/commit/640509f8689a59d4620ec7d95bd0ff1cbc40d81b

--

**Comment by wincent** [comment]
I don't know the cause yet but I just took a look at your dotfiles. Awesome overengineering there, much like my own!

**Comment by frioux** [comment]
Glad you like it! Check out bin/fressh, I'm pretty proud of that. I alias
ssh to that and now servers all feel like home 😉

--

**Comment by CaninoDev** [comment]
Has this issue been resolved? I face a similar problem with terminator. . 
![image](https://cloud.githubusercontent.com/assets/16412897/24220900/5a777670-0f09-11e7-905d-e52ff0083325.png)

**Comment by coquizen** [comment]
While I have experienced frioux's artifacts problem, I haven't been able to consistently reproduce it. 

I do get a repetition of the tmux modeline however as thus: 
![image](https://cloud.githubusercontent.com/assets/16412897/24220969/a6952a5c-0f09-11e7-9728-bd93f1d9d9e1.png)

**Comment by frioux** [comment]
I just rolled back to before that commit, fwiw.

**Comment by wincent** [comment]
@CaninoDev: is the repetition consistently reproducible?

> I just rolled back to before that commit, fwiw.

And if it is consistently reproducible, does it go away when you roll back?

**Comment by coquizen** [comment]
Yes. The tmux line would repeat without input.
EDIT: This might largely be a terminator issue and not a Terminus issue.

**Comment by wincent** [comment]
> This might largely be a terminator issue and not a Terminus issue.

Yes, could be. If so, it would be nice to:

- Figure out the cause and fix it upstream in Terminator.
- Make some defensive change to Terminus that makes things work even in the presence of an old/unpatched version of Terminator.

Do you have any idea of what the exact upstream issue is?

**Comment by wincent** [comment]
A related question: is there some environment variable or something that Terminus can check at runtime to detect that it is running inside Terminator?

**Comment by frioux** [comment]
Looks like `TERMINATOR_UUID=urn:uuid:f746e224-4f5a-495c-b180-51785500a463` on mine.

**Comment by wincent** [comment]
I am not sure if it is the right thing to do to turn off cursor shape changes automatically when running in Terminator, but if you wanted to do it yourself you could add something like this to your `~/.vimrc`:

```
let g:TerminusCursorShape=0
```

**Comment by wincent** [comment]
As I said, not sure if it's the right thing to do, but if we want to, we could use something like https://github.com/wincent/terminus/commit/bad3debf7c688e82a7669bb3559c29c39120f066 (just pushed to the `terminator` branch) to disable support for cursor shape changes in Terminator.

**Comment by coquizen** [comment]
Both Prioux's bug and mine are independent of .vim (at least on my end).

**Comment by coquizen** [comment]
So updating Terminator to v1.91 via ppa:gnome-terminator/nightly-gtk3 solves the problems of artifacts. However, tmux modeline now disappears. But I suppose this is outside the scope of terminator as this is meant to replace tmux.

**Comment by frioux** [comment]
I just updated to fix a different issue and I think this is fixed now.  Give me a few days and I'll close it.

**Comment by wincent** [comment]
Glad to hear you got it fixed.
