### ISSUE TITLE
Focus Reporting does not seem to be working consistently anymore

### ISSUE THREAD

**Issue by alxyang** [wincent/terminus#21]
Recently (maybe a few months ago?) I have observed that the focus reporting feature does not work nearly as well as it used to, in many cases it does not work at all when switching between tmux panes etc.

Here is my `vim --version` output
https://gist.github.com/alxyang/fcf57388d27ca04f92390572ab219dff

tmux -V => 2.2

Let me know if there is any other information i can provide.
Feel free to explore my devserver if you'd like ;)

**Comment by wincent** [comment]
You're probably seeing something that I noticed a while back and fixed on the `next` branch in https://github.com/wincent/terminus/commit/3647ce0bd0 — I should probably merge it into the `master` branch and cut a new release.

**Comment by wincent** [comment]
I merged `next` into `master` and cut the 1.2 release. Should hopefully fix the issue you've been seeing.

**Comment by alxyang** [comment]
thanks!

**Comment by alxyang** [comment]
in case anyone else comes across this, I also needed to set `set -g focus-events on` in my ~/.tmux.conf

**Comment by wincent** [comment]
We might want to add that to the docs, if it's not there already.
