### ISSUE TITLE
Focus reporting not working in bare iTerm nor tmux

### ISSUE THREAD

**Issue by rlue** [wincent/terminus#28]
Focus reporting isn't working on my setup, for some reason. Terminus' other features (dynamic cursor & ‘bracketed paste’ mode) are working just fine. I'm on:

* Mac OS 10.11 El Capitan
* iTerm2 Build 3.0.15
* MacVim / vim 8.0 with patches 1-596
* tmux 2.5

I have the following file set up to test it out.

```viml
" ~/.vim/plugin/foo.vim
augroup foo
  autocmd!
  autocmd FocusGained * echo 'hello!'
  autocmd FocusLost * echo 'goodbye!'
augroup END
```

Being located in the `/plugin` directory, it's loaded automatically on launch. It produces the expected output in GUI vim (MacVim), but nothing in the terminal. I've tried in both the bare terminal (where I even tried setting `g:TerminusAssumeITerm`) and tmux (where I made sure to `set -g focus-events on`, per #21).

Any insight would be greatly appreciated.

**Comment by rcarraretto** [comment]
@rlue fwiw, I was having a similar issue and I solved it via https://github.com/wincent/terminus/issues/23#issuecomment-334972338. not sure if it helps you.

**Comment by rlue** [comment]
Unfortunately, it looks like we're dealing with separate issues. Thanks for the suggestion, though!

**Comment by wincent** [comment]
Sorry for never replying to this. I'm going to close it due to inactivity. 😔
