### ISSUE TITLE
Copy to clipboard broken in iTerm2

### ISSUE THREAD

**Issue by jabbrahn** [wincent/terminus#3]
# Steps to reproduce
- open any file in vim
- select text
- copy text to clipboard (⌘C)
# Expected behaviour
- the clipboard contains the selected text
# Current behaviour
- the content of the clipboard is unchanged

**Comment by jabbrahn** [comment]
Enabling 'Copy on select' and temporarily disabling 'Enable xterm mouse reporting' by pressing the ⌥ key before (and while) making a selection works around the issue.

**Comment by wincent** [comment]
Yep, that sounds right. I'll add a mention of this to the trouble-shooting section in the docs.
