### ISSUE TITLE
Conflict with vdebug (focus related?)

### ISSUE THREAD

**Issue by mblarsen** [wincent/terminus#30]
I'm using the https://github.com/joonty/vdebug plugin for debugging.  (Garethp/vdebug python3 branch)

> Vdebug is a new, fast, powerful debugger client for Vim

You start the debugger in listen mode and then you switch to a browser window to trigger a request. In my case to a PHP script.

Unfortunately, terminus triggers something that cancels the debugger when you switch away from the terminal (iTerm2). The key to cancel the debugger listening is ctrl-c. I don't know if that is a clue to anything.

Any pointers to where I could start debugging this issue?

ps: love your vim vids on YouTube 👍

**Comment by mblarsen** [comment]
FYI it also happens with https://github.com/tmux-plugins/vim-tmux-focus-events — another focus related plugin. I'm starting to think that the issues should be raised with vdebug instead.

**Comment by wincent** [comment]
Ok, thanks @mblarsen.
