### ISSUE TITLE
Error when FocusGained event fires in the commandline history window

### ISSUE THREAD

**Issue by frioux** [wincent/terminus#33]
To repro:

1. Press `q:` or `:<C-f>`
2. Mouse in and out of window

You should get an error something like this:

```
Error detected while processing FocusGained Auto commands for "*":
E11: Invalid in command-line window; <CR> executes, CTRL-C quits: checktime
```

**Comment by wincent** [comment]
Thanks for the error report, @frioux. I've seen this before but have been too lazy to fix it. Will put up a proposed fix in a sec.
