### ISSUE TITLE
plugin interferes with vimcrypt

### ISSUE THREAD

**Issue by ri-aje** [wincent/terminus#40]
terminus disables the password prompt from vimcrypt, making vim not able to open a vim encrypted file. 

here is a min repro vimrc
```
set nocompatible
call plug#begin('~/.vim/bundle')
 Plug 'wincent/terminus'
call plug#end()
```

repro with these steps.
1. `vim -x test.txt`
2. enter dummy password as prompted.
3. type something in the file.
4. `:w` to save the file and exit vim.
5. `vim -u NONE test.txt` to open the file with vanilla vim, note vim prompts for password and decrypts the file correctly.
5. `vim -u vimrc test.txt` to open the file with the min repro vimrc, note vim doesn't prompt for password anymore instead displays a buffer full of binary garbage.
6. commenting out `Plug 'wincent/terminus'` would also make the previous step work as expected. so I think the plugin somehow messed up vim to not prompt for password.

**Comment by wincent** [comment]
What's your OS and terminal? Are you inside tmux or screen?

**Comment by ri-aje** [comment]
> What's your OS and terminal? 

ubuntu 18.04 and terminator 1.91. I also just tried it on tilda and had the same issue.

> Are you inside tmux or screen?

I am not, just on regular terminal. in case it matters, my vim is 8.1 patches: 1-1512.

**Comment by wincent** [comment]
I can repro this. If I comment out [this line](https://github.com/wincent/terminus/blob/0c826f1eb31f68648fa82cb25ed06031dc846a44/plugin/terminus.vim#L115) the prompt doesn't get eaten. Somehow, turning on focus reporting is causing the prompt to get dismissed. My hunch is that a focus reporting event is received at startup, which actually ends up being interpreted as input to the prompt. You can see this by commenting out [this line](https://github.com/wincent/terminus/blob/0c826f1eb31f68648fa82cb25ed06031dc846a44/plugin/terminus.vim#L122) instead.

I guess the workaround may be to only activate focus reporting after the `VimEnter` autocmd fires.

**Comment by wincent** [comment]
So I tried activating focus reporting only after `VimEnter` fires. Sadly, that's too late. It seems that if you change `t_ti` after startup it's already too late; Vim won't send the sequence to the terminal, which means that focus reporting won't work.

As it stands, Vim seems to be sending the sequence to terminal presumably after showing the prompt and the prompt gets filled with a garbage encryption key. I don't think that's a Vim bug though: on my system this only happens in tmux but not outside it, which makes it seem that when tmux gets the sequence that turns on focus reporting, it immediately sends a focus event — outside tmux, iTerm doesn't do that, which means it is terminal dependent.

I'm not sure how to work around this. Note that if you just open Vim and then do `:e test.txt` the prompt appears just fine.

**Comment by ri-aje** [comment]
@wincent thanks for the prompt replies. after you mentioned it, I tried it on a few other envs. indeed, on osx with the builtin terminal and iterm2, vim crypt works just fine, with or without tmux. on ubuntu, vimcrypt has the bug under terminator, again with or without tmux, whereas on tilda, vimcrypt works under tmux but has the bug without tmux. the landscape appears pretty uneven. 

though one critical difference I have is that `e test.txt` doesn't make any difference, so when this bug manifests, I really don't have another way than bypassing my vimrc or disabling terminus. 

as for workaround, is it possible to detect vimcrypt files and bypass [this line](https://github.com/wincent/terminus/blob/0c826f1eb31f68648fa82cb25ed06031dc846a44/plugin/terminus.vim#L115)? since I presume there isn't much complicated use cases with vimcrypt. I can also do this in my vimrc to disable terminus for vimcryt files, but I am not sure how to detect them with vim script. if you know, please share. thanks.

**Comment by wincent** [comment]
> though one critical difference I have is that e test.txt doesn't make any difference, so when this bug manifests, I really don't have another way than bypassing my vimrc or disabling terminus.

That's really weird. So you're saying you open Vim, and the when it is idle, you do `:e test.txt`, and you see no prompt? Does `:messages` show (something like) this aftewards?

```
Need encryption key for "/tmp/test.txt"
"/tmp/test.txt" [noeol][blowfish2] 1L, 11C
```

I don't know if it is possible to detect vimcrypt filed, and even if it is, it might be too late by the time you can...

**Comment by ri-aje** [comment]
> > though one critical difference I have is that e test.txt doesn't make any difference, so when this bug manifests, I really don't have another way than bypassing my vimrc or disabling terminus.
> 
> That's really weird. So you're saying you open Vim, and the when it is idle, you do `:e test.txt`, and you see no prompt? 

correct, i.e., `e test.txt` gives identical behavior than `vim test.txt` initially. I did try that before filing and if it were to have worked, I probably won't have filed this bug since that's a reasonable workaround and I don't need vimcrypt that often anyway.

> Does `:messages` show (something like) this aftewards?

after `e test.txt` it showed

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Need encryption key for "test.txt"
"test.txt" [noeol][converted][blowfish2] 1L, 18C
"test.txt" [noeol][converted][blowfish2] 1L, 18C
```

I believe the first repetition is from the initial vim command and the second from the edit ex command.

> 
> ```
> Need encryption key for "/tmp/test.txt"
> "/tmp/test.txt" [noeol][blowfish2] 1L, 11C
> ```
> 
> I don't know if it is possible to detect vimcrypt filed, and even if it is, it might be too late by the time you can...

gotcha.

in case it helps anyone hitting the same bug, I found a workaround which is to use gui vim, aka `gvim` and that correctly prompts me for password even with terminus enabled. even though that forces to go out of terminal, it's good enough for my casual usage.

**Comment by wincent** [comment]
I see. It's because you already opened it with `vim test.txt` then, right? If you'd done `vim` then `:e test.txt` It would have worked, I think.

**Comment by ri-aje** [comment]
> I see. It's because you already opened it with `vim test.txt` then, right? If you'd done `vim` then `:e test.txt` It would have worked, I think.

indeed it worked this way. thanks.

**Comment by wincent** [comment]
Given that this one is gnarly and workarounds existing, going to close it out.
