### ISSUE TITLE
Always sets autoread

### ISSUE THREAD

**Issue by pkrumins** [wincent/terminus#42]
Hi Greg,

Thanks for creating this awesome plugin!

I'm opening this issue because the plugin automatically and unconditionally sets `autoread` at https://github.com/wincent/terminus/blob/master/plugin/terminus.vim#L15.

The default value of `autoread` is off and as the plugin is loaded after user's `.vimrc`, it always sets it to true. This makes it impossible to keep autoread off. I prefer autoread to be off because if an external process changes a file and autoread is on, then there is no notification about it and vim instantly and unexpectedly reloads the file.

At the moment, I solved this problem for myself by deleting the `set autoread` line so that it's off by default.

Could you please add an option to enable/disable `autoread` so that it can be configured?

Peter

**Comment by wincent** [comment]
I don't think this needs an option. You can override it with something like:

```
mkdir -p ~/.vim/after/plugin
echo 'set noautoread' >> ~/.vim/after/plugin/terminus.vim
```

Let me know if that doesn't work for you, but I'm going to close this anticipating that it probably will.

**Comment by wincent** [comment]
Funny thing to note: `'autoread'` default to "on" in Neovim, "off" in Vim.

**Comment by pkrumins** [comment]
Hi Greg,

Thanks for your response. I was not aware of the after directory. I just tried it and it works great! 

> Funny thing to note: 'autoread' default to "on" in Neovim, "off" in Vim.

Good to know!

Peter
