### ISSUE TITLE
Add support for cursor shape 2 (underline)

### ISSUE THREAD

**Issue by itaiferber** [wincent/terminus#5]
Currently, terminus returns the cursor shape on insertion end to cursor shape 0 (box)

```
let s:end_insert="\<Esc>]50;CursorShape=0\x7"
```

 but it would be nice to have a setting that would allow it to set the cursor shape to shape 2 (underline, the default option)

```
let s:end_insert="\<Esc>]50;CursorShape=2\x7"
```

This is easy enough to change manually by editing `terminus.vim`, but it would be nice to have the option supported by default. :smile:

**Comment by wincent** [comment]
Yeah, I agree that this should be an option.

> underline, the default option

Are you sure underline is the default? The fact that the block shape is "0", and the first listed shape in [the docs](http://www.iterm2.com/documentation-escape-codes.html), makes me think it is the default.

Either way, I think you're right; we should whip something up.

**Comment by wincent** [comment]
This is now on the `master` branch, so closing. Thanks for the suggestion!

**Comment by itaiferber** [comment]
Sorry about that — should've been more careful. It's the cursor shape I've had for as long as I remember, and the one that appears first in the list in the UI, so I assumed incorrectly.

In any case, thanks for getting that in there so fast! Much appreciated. :+1: :smiley:
